apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-demo-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: deployment-alerts
      rules:
        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas != kube_deployment_status_replicas_available
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Deployment {{ $labels.deployment }} replica mismatch"

        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total[15m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is crash-looping"
